# 服务端口
server:
  port: 9093
---
# mysql数据配置
datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://192.168.3.135:3306/lanyue_base?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: addplus
  password: addPlus@520
---
# mongodb配置
mongo:
  host: 192.168.3.135
  port: 27017
  database: lanyue
  username: addplus
  password: addplus@520
---
# redis配置
spring:
  redis:
    nodes: 192.168.3.135:6388,192.168.3.135:6389
    model: master #启用模式  cluster：集群  master:单/多个节点
    password: 1q2w3e4R
---
#logging
logging:
  level:
    com:
      addplus:
        api:
          mapper: DEBUG